# Define your model configurations
model_configurations = [
    {
        "index": 0,
        "name": "April 13_4 1st Model",
        "cfg": "computer_vision/pyCode/Models/April_2nd/v4_1st/custom-yolov4-tiny-detector.cfg",
        "weights": "computer_vision/pyCode/Models/April_2nd/v4_1st/custom-yolov4-tiny-detector_best.weights",
        "names": "computer_vision/pyCode/Models/April_2nd/v4_1st/obj.names",
    },
    {
        "index": 1,
        "name": "April 13_4 2nd Model",
        "cfg": "computer_vision/pyCode/Models/April_2nd/v4_2nd/custom-yolov4-tiny-detector.cfg",
        "weights": "computer_vision/pyCode/Models/April_2nd/v4_2nd/custom-yolov4-tiny-detector_best.weights",
        "names": "computer_vision/pyCode/Models/April_2nd/v4_2nd/obj.names",
    },
    {
        "index": 2,
        "name": "April Best 4k dataset",
        "cfg": "computer_vision/pyCode/Models/Best/4k_Dataset/custom-yolov4-tiny-detector.cfg",
        "weights": "computer_vision/pyCode/Models/Best/4k_Dataset/custom-yolov4-tiny-detector_best.weights",
        "names": "computer_vision/pyCode/Models/Best/4k_Dataset/obj.names",
    },
    {
        "index": 1,
        "name": "April 36K Epochs",
        "cfg": "computer_vision/pyCode/Models/Best/36_epoch/custom-yolov4-tiny-detector.cfg",
        "weights": "computer_vision/pyCode/Models/Best/36_epoch/custom-yolov4-tiny-detector_best.weights",
        "names": "computer_vision/pyCode/Models/Best/36_epoch/obj.names",
    },
    {
        "index": 2,
        "name": "April Model eight",
        "cfg": "computer_vision/pyCode/Models/April/eight_april/custom-yolov4-tiny-detector.cfg",
        "weights": "computer_vision/pyCode/Models/April/eight_april/custom-yolov4-tiny-detector_best.weights",
        "names": "computer_vision/pyCode/Models/April/eight_april/obj.names",
    },
    {
        "index": 3,
        "name": "April Model the first",
        "cfg": "computer_vision/pyCode/Models/April/first_of_april/custom-yolov4-tiny-detector.cfg",
        "weights": "computer_vision/pyCode/Models/April/first_of_april/custom-yolov4-tiny-detector_best.weights",
        "names": "computer_vision/pyCode/Models/April/first_of_april/obj.names",
    },
    {
        "index": 4,
        "name": "March 1st Model",
        "cfg": "computer_vision/pyCode/Models/March/1st/custom-yolov4-tiny-detector.cfg",
        "weights": "computer_vision/pyCode/Models/March/1st/custom-yolov4-tiny-detector_best.weights",
        "names": "computer_vision/pyCode/Models/March/1st/obj.names",
    },
    {
        "index": 5,
        "name": "March 2nd Model",
        "cfg": "computer_vision/pyCode/Models/March/2nd/custom-yolov4-tiny-detector.cfg",
        "weights": "computer_vision/pyCode/Models/March/2nd/custom-yolov4-tiny-detector_best.weights",
        "names": "computer_vision/pyCode/Models/March/2nd/obj.names",
    },
    {
        "index": 6,
        "name": "October Model",
        "cfg": "computer_vision/pyCode/Models/October/custom-yolov4-tiny-detector.cfg",
        "weights": "computer_vision/pyCode/Models/October/custom-yolov4-tiny-detector_best.weights",
        "names": "computer_vision/pyCode/Models/October/obj.names",
    },
]
